version: '2'
services:
  glassfish:
    build: ../images/glassfish
    environment:
     - ADMIN_PASSWORD=glassfish
    ports:
     - "8080:8080"
     - "4848:4848"
    links:
     - mysql:db
  mysql:
    build: ../images/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "3306:3306"
  phpmyadmin:
    build: ../images/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=adminpw
    ports:
     - "6060:80"
    links:
     - mysql:db